### ISSUE TITLE
[Feat] Alarm API

### ISSUE THREAD

**Issue by sonshn** [UMC-CommonPlant/CommonPlant-Server-Refactoring#103]
## 🚀이슈 제목
- Alarm API

## 📝이슈 설명
- 연관 이슈: #17 
-

## ✨작업 내용
- [X] 새로운 작업 내용
- [X] 기존 코드 변경

## ☑️To-Do
- [ ] **식물 등록**한 날에 따라 불러오기
