### ISSUE TITLE
[Feat] Guest Login Update

### ISSUE THREAD

**Issue by uhyunglee** [UMC-CommonPlant/CommonPlant-Server-Refactoring#104]
## 🚀이슈 제목
게스트로그인 (업데이트)
## 📝이슈 설명
게스트로그인 새로운 브랜치 생성 
## ✨작업 내용
- [ ] 새로운 작업 내용
- [ ] 기존 코드 변경

## ☑️To-Do

- [ ] 엔드포인트 접근제한 처리
- [ ] 403 에러 예외처리
