### ISSUE TITLE
[Refactor] Login 로직수정

### ISSUE THREAD

**Issue by uhyunglee** [UMC-CommonPlant/CommonPlant-Server-Refactoring#105]
## 🚀이슈 제목
로그인 로직수정
## 📝이슈 설명
애플로그인으로 회원가입시 email을 입력안해도 유저 조회가능하게 변경 
(provider_id로 유저조회 가능하게 변경)

## ✨작업 내용
- [ ] 새로운 작업 내용
- [x] 기존 코드 변경

## ☑️To-Do

- [ ] 회원가입시  DB에 provider_id 저장
