### ISSUE TITLE
[Fix] Firebase 설정 수정

### ISSUE THREAD

**Issue by sonshn** [UMC-CommonPlant/CommonPlant-Server-Refactoring#15]
## 🚀이슈 제목
[Fix] Firebase 설정 수정

## 📝이슈 설명
Client Key의 이름이 코드에 작성되어있어 수정

## ✨작업 내용
- [X] 새로운 작업 내용: Firebase 프로젝트를 새로 생성하고, 새 Client Key를 생성함
- [X] 기존 코드 변경: Client Key의 이름이 코드에 작성되어있어 수정

## ☑️To-Do
- [X] `resources`아래에 파일 추가
