### ISSUE TITLE
[Feat] Plant API

### ISSUE THREAD

**Issue by sonshn** [UMC-CommonPlant/CommonPlant-Server-Refactoring#26]
## 🚀이슈 제목
Plant API

## 📝이슈 설명
Plant 도메인 API 개발

## ✨작업 내용
- [X] 새로운 작업 내용
- [ ] 기존 코드 변경

## ☑️To-Do
- [ ] 식물 추가
- [ ] 식물 수정
- [ ] 같은 장소의 식물 리스트 조회
- [ ] 식물 조회
