### ISSUE TITLE
[Chore] : Place Friends API

### ISSUE THREAD

**Issue by uhyunglee** [UMC-CommonPlant/CommonPlant-Server-Refactoring#56]
## 🚀이슈 제목
Place API
## 📝이슈 설명
장소 참여 인원 추가 수정
## ✨작업 내용
- [ ] 새로운 작업 내용
- [x] 기존 코드 변경

## ☑️To-Do

- [x] Place에 다른 유저 초대
- [ ]  장소에 유저가 이미 존재할 때 예외처리
- [ ]  존재하지 않는 유저일 때 예외처리
