### ISSUE TITLE
[FEAT] : Place API 메인화면

### ISSUE THREAD

**Issue by uhyunglee** [UMC-CommonPlant/CommonPlant-Server-Refactoring#58]
## 🚀이슈 제목
메인화면
## ✨작업 내용
- [ ] 새로운 작업 내용
- [ ] 기존 코드 변경

## ☑️To-Do

- [x] PlaceList 등록된 시간 순으로 정렬
- [x] 장소정보 - 사진, 이름, 참여인원 수, 등록식물 수
- [x] PlantList 물주기 짧은 순으로 정렬
- [x] 식물정보 - 식물사진, 이름, 속한 장소, 인원 수, 물주기
