### ISSUE TITLE
[REFACTOR] Version 1의 기획 외의 필요없는 로직 삭제

### ISSUE THREAD

**Issue by hweyoung** [UMC-CommonPlant/CommonPlant-Server-Refactoring#59]
## 🚀이슈 제목
Version 1의 기획 외의 필요없는 로직 삭제

## ✨작업 내용
- [ ] 배포 버전 우선순위 정한 후 버전별 필요한 기능 분리
- [ ] Story & QnA 관련 로직 삭제

## ☑️To-Do

- [ ] 추가된 기획에 관련된 로직 지우기
- [ ] Comment 삭제
- [ ] Keyword 삭제
- [ ] Likes 삭제
- [ ] Ona 삭제
- [ ] Story 삭제
