### ISSUE TITLE
[Feat] CI/CD 및 Nginx 무중단 배포 설정

### ISSUE THREAD

**Issue by hweyoung** [UMC-CommonPlant/CommonPlant-Server-Refactoring#61]
## 🚀이슈 제목
CI/CD 및 Nginx 무중단 배포 설정

## ☑️To-Do
- [ ] GithubAction / S3 / CodeDeploy CI/CD 배포 설정
- [ ] develop, release, master 브랜치 설정
- [ ] master 브랜치 CI/CD 설정
- [ ] Nginx 무중단 배포 설정
