### ISSUE TITLE
[Fix] Fix getUser Error

### ISSUE THREAD

**Issue by uhyunglee** [UMC-CommonPlant/CommonPlant-Server-Refactoring#82]
## 🚀이슈 제목
 사용자 정보가 안뜨는 문제
## 📝이슈 설명
헤더 토큰에서 사용자 정보추출에 오류가 발생하여 생기는 문제 해결 
## ✨작업 내용
- [ ] 새로운 작업 내용
- [x] 기존 코드 변경

## ☑️To-Do

- [x] getUser 메서드 수정
- [ ] 이름으로 조회하는 메서드와 분리
